package com.alfianyusufabdullah.chatyuk.presentation.chatroom

import com.alfianyusufabdullah.chatyuk.data.repository.database.MessageRepositoryCallback

interface ChatRoomView : MessageRepositoryCallback